version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: sistema_livros_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: sistema_livros
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
